services:
  source.factory:
    class: Vainyl\Data\Factory\SourceFactory
  source.factory.logger:
    decorates: source.factory
    arugments: ['@source.factory.logger.inner', '@logger']
  source.storage:
    parent: storage.proxy
    class: Vainyl\Data\Storage\SourceStorage
    arguments: ['@source.factory']