services:
  source.factory:
    class: Vainyl\Data\Factory\SourceFactory
  source.factory.logger:
    decorates: source.factory
    class: Vainyl\Data\Factory\Decorator\LoggerSourceFactoryDecorator
    arugments: ['@source.factory.logger.inner', '@logger.source']
  source.storage:
    class: Vainyl\Data\Storage\SourceStorage
    arguments: ['@storage.prototype', '@source.factory']